variable "llave_ssh" {}
variable "server_role" {}
variable "usuario_ansible" {}
variable "usuario_admin" {}
variable "contrasena_user" {}
variable "proyecto" {}
variable "los_IDs_subredes" {}
variable "ip_fija_privada" {}
variable "los_SG" {}
variable "AZs" {}
variable "server_ami" {}
variable "region" {}
variable "tipo_instancia" {}
