variable "llave_ssh" {}
variable "server_role" {}
variable "usuario_ansible" {}
variable "usuario_sonarqb" {}
variable "contrasena_user" {}
variable "postgres_sonar_user" {}
variable "postgres_sonar_pw" {}
variable "postgres_db_name" {}
variable "proyecto" {}
variable "los_IDs_subredes" {}
variable "ip_fija_privada" {}
variable "los_SG" {}
variable "AZs" {}
variable "win_server_ami" {}
variable "region" {}
variable "tipo_instancia" {}
