variable "llave_ssh" {}
variable "server_role" {}
variable "proyecto" {}
variable "los_IDs_subredes" {}
variable "ip_fija_privada" {}
variable "los_SG" {}
variable "AZs" {}
variable "win_server_ami" {}
variable "region" {}
variable "tipo_instancia" {}