variable "llave_ssh" {}
variable "server_master" {}
variable "server_cliente" {}
variable "usuario_app" {}
variable "pw_user_app" {}
variable "proyecto" {}
variable "los_IDs_subredes" {}
variable "ip_nodos_master" {}
variable "ip_nodos_client" {}
variable "los_SG" {}
variable "AZs" {}
variable "win_server_ami" {}
variable "region" {}
variable "tipo_instancia" {}