variable "llave_ssh" {}
variable "server_role" {}
variable "usuario_ansible" {}
variable "contrasena_user" {}
variable "proyecto" {}
variable "los_IDs_subredes" {}
variable "ip_fija_privada" {}
variable "los_SG" {}
variable "AZs" {}
variable "win_server_ami" {}
variable "region" {}
variable "tipo_instancia" {}

variable "ip_server_docker" {}
variable "ip_server_tomcat" {}
variable "ip_server_ansible" {}
variable "ip_server_jenkins_slave" {}
variable "ip_server_k8s_master" {}
variable "ip_server_k8s_worker_1" {}
variable "ip_server_k8s_worker_2" {}
variable "ip_server_puppet_master" {}
variable "ip_server_puppet_client" {}
variable "ip_server_maven" {}